Object.assign(
  module.exports,
  require('./courses'),
  require('./classes'),
  require('./children'),
  require('./registrations'),
  require('./families'),
  require('./login'),
  require('./users'),
  require('./reports'),
  require('./years'),
  require('./teachers')
);
