Object.assign(
  module.exports,
  require("./courses"),
  require("./classes"),
  require("./children"),
  require("./enrollments"),
  require("./families"),
  require("./login"),
  require("./payments"),
  require("./registrations"),
  require("./reports"),
  require("./teachers"),
  require("./users"),
  require("./years")
);
